### ISSUE TITLE
I get c_typs error when I run any/all examples in the framework

### ISSUE THREAD

**Issue by hussainalmahmud** [cmlasu/dMazeRunner#1]
**Hi, after I installed and followed all the instructions. I now want to run the scripts. 
after running this line**
python run_optimizer.py --frontend mxnet --model resnet18_v1 --auto-optimize

**I get this error:**
Traceback (most recent call last):
  File "run_optimizer.py", line 1, in <module>
    from matplotlib import pyplot as plt
  File "/home/hussain/.local/lib/python3.7/site-packages/matplotlib/__init__.py", line 138, in <module>
    from . import cbook, rcsetup
  File "/home/hussain/.local/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 31, in <module>
    import numpy as np
  File "/home/hussain/.local/lib/python3.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/home/hussain/.local/lib/python3.7/site-packages/numpy/core/__init__.py", line 99, in <module>
    from . import _dtype_ctypes
  File "/home/hussain/.local/lib/python3.7/site-packages/numpy/core/_dtype_ctypes.py", line 26, in <module>
    import ctypes
  File "/usr/lib64/python3.7/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: cannot import name 'Union' from '_ctypes' (/home/hussain/dMazeRunner/tvm/nnvm/python/nnvm/_ctypes/__init__.py)

Can someone please help me to solve this issue because I can't get it solved no matter what I did to the code.

**Comment by yb-kim** [comment]
It looks like your system does not have `libffi` library, which is required to import `_ctypes`. 
`_ctypes` should be imported from `/home/hussain/.local/lib/python3.7/...` in your case, not from `/home/hussain/dMazeRunner/tvm/nnvm/python/nnvm/_ctypes/init.py`.

In Ubuntu, you can install `libffi` packages using `sudo apt install libffi-dev`.
In CentOS, you can use `sudo apt install libffi-devel`.
For more information, or you're using other systems, please google `ModuleNotFoundError: No module named '_ctypes'`.
